#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/sbin/ucode-gps

service_triggers() {
	procd_add_reload_trigger gps
}

start_service() {
	local tty="$(uci -q get gps.@gps[-1].tty)"
	local baudrate="$(uci -q get gps.@gps[-1].baudrate || echo 0)"
	local atime="$(uci -q get gps.@gps[-1].adjust_time || echo 0)"
	local debug="$(uci -q get gps.@gps[-1].debug || echo 0)"
	local disabled="$(uci -q get gps.@gps[-1].disabled || echo 0)"

	[ "$disabled" = "0" ] || return
	[ "$tty" ] || return

	case "$tty" in
		"/"*)
			;;
		*)
			tty="/dev/$tty"
			;;
	esac

	procd_open_instance
	procd_set_param command "$PROG"
	[ "$baudrate" -eq 0 ] || procd_append_param command -b "$baudrate"
	[ "$atime" -eq 0 ] || procd_append_param command -a
	[ "$debug" -eq 0 ] || procd_append_param command -d "$debug"
	procd_append_param command "$tty"
	procd_set_param respawn
	procd_close_instance
}
