#!/bin/sh /etc/rc.common

START=80
STOP=01

USE_PROCD=1

PROG=/usr/sbin/udeviced

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param file /etc/config/system
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}

service_running() {
	ubus -t 10 wait_for device
}

service_triggers() {
	procd_add_reload_trigger "system"
}

reload_service() {
	ubus call device reload
}
